version: "3.7"

services:

  app:
    container_name: app
    build:
      context: ./services/user-service
    depends_on:
      - mysql_db
    ports:
      - "8081:8081"
    networks:
      - netw

   config-app:
    container_name: config-app
    build:
      context: ./services/config
    ports:
      - "8181:8181"
    networks:
      - netw

  mysql_db:
    image: mysql:8
    networks:
      - netw
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_PASSWORD=user"
      - "MYSQL_USER=user"
      - "MYSQL_DATABASE=pshop"
      - "MYSQL_ROOT_HOST=%" 
    volumes:
      - "./my-db-data:/var/lib/mysql"
      - "./mysql:/docker-entrypoint-initdb.d"
volumes:
  my-db:
networks:
  netw:

