version: "3"

services:
  
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE= pshop
      - MYSQL_USER=user
      - MYSQL_PASSWORD= user
    ports:
      - 3308:3306
    volumes:
      - /data/db



  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    command: sh -c 'sleep 100 &&  java -jar user-service.jar'
    depends_on:
      - db
    ports:
      - 8081:8081
    volumes:
      - /data/user-service
    links:
      - db