server:
  port: 8181
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hamzahda/website-config-server-repository
          skipSslValidation: true